### ISSUE TITLE
Not muting playing notes

### ISSUE THREAD

**Issue by martin-minovski** [schellingb/TinySoundFont#9] opened 2017-10-22 09:45 UTC
Hi again! Playing a single note (note_on, note_off) quickly results in sharp reverb cut off. I found a temporary hack which fixed this (maybe not ideal but works)

tsf.h commit 7f29067 line 1160 onwards:
```
	for (v = f->voices, vEnd = v + f->voiceNum; v != vEnd; v++)
	{
		if (v->playingPreset != preset_index) continue;
		#ifndef SET_LOSSLESS
		if (v->playingKey == key) tsf_voice_endquick(v, f->outSampleRate);
		if (v->region->group) haveGroupedNotesPlaying = TSF_TRUE;
		#endif
	}
```

You can hear the difference here: [https://soundcloud.com/martin-minovski/tsf-test](https://soundcloud.com/martin-minovski/tsf-test)
Ignore the buffer underruns. If I pre-render the samples instead, it sounds perfect with the hack enabled.

Could be nice to have that as a setting variable which can change during runtime. 👍 

Cheers

Martin

**Comment by schellingb** [comment] 2017-10-22 16:19
Hey there!
Thanks for all your great inputs.
What do you think of my recent commit b9a4de3:
```
Handle note_on/off more like the MIDI standard suggests:
- Change note_on with a velocity of 0 to be handled as note_off
- Change note_on so it doesn't cancel previous note_on of the same preset/key
- Change note_off so it only stops a single corresponding note_on and not all notes playing on the same preset/key
```
The previous behavior of note_on/off was taken over from SFZero which does not seem to match the MIDI standard descriptions I can find. They require a corresponding note_off for every note_on. My change ends up stopping only the voices of the first played note_on. I was unsure if it would be better to stop the most recent one. Didn't find a ruling on that part. Funnily not even FluidSynth seems to do it correctly...

The handling of v->region->group (which you #ifdef'd out as well) is still untouched as it matches the description in the [SF2 specs](http://freepats.zenvoid.org/sf2/sfspec24.pdf):
```
This parameter provides the capability for a key depression in a given instrument to 
terminate the playback of other instruments.  This is particularly useful for 
percussive instruments such as a hi-hat cymbal.  An exclusive class value of zero 
indicates no exclusive class; no special action is taken.  Any other value indicates 
that when this note is initiated, any other sounding note with the same exclusive class 
value should be rapidly terminated.  The exclusive class generator can only appear at 
the instrument level.  The scope of the exclusive class is the entire preset.  In other 
words, any other instrument zone within the same preset holding a corresponding 
exclusive class will be terminated. 
```

Does that change do anything good for your test?
Thanks again for using the lib!
\ Bernhard

**Comment by frabert** [comment] 2017-10-23 18:08
@schellingb The last commit introduced a lot of notes getting "stuck" playing, whereas before I had no issues

**Comment by schellingb** [comment] 2017-10-24 01:36
@frabert Interesting... I assume you don't have a note_off for every single note_on? Or maybe there is a bug... I'll look into it and hope to get back soon with either an option to make the note_off behave as before or a fix. Sorry for the inconvenience!

**Comment by frabert** [comment] 2017-10-24 06:14
I generate the note_off programmatically, so there should never be note_ons without note_off

**Comment by schellingb** [comment] 2017-10-24 14:42
@frabert Oh man, sorry for my accusation...
Turned out to be a bug (or rather complete oversight) in the new note_off handling. Of course note_off can't just end the earliest playing voice without checking its state because even after ending it is still playing the release envelope. It should be good now.
Glad you popped in here :-)
Thanks!!

**Comment by frabert** [comment] 2017-10-24 14:44
@schellingb No problem man, no offense taken! Thank you very much for the snappy responses and support!

**Comment by frabert** [comment] 2017-10-24 15:38
UPDATE: Unfortunately I can still reproduce the problem...

**Comment by schellingb** [comment] 2017-10-24 16:47
@frabert The fix ended up not ignoring notes in the sustained state as well, instead of just the release state in note_off... My explanation above was correct but sadly not the code. Sigh...
Third times the charm?
Thanks again for testing!!

**Comment by frabert** [comment] 2017-10-24 17:25
@schellingb The last commit seems to have fixed the behavior!

**Comment by schellingb** [comment] 2017-10-31 15:30
Awesome. Closing this one then!

**Closed by schellingb** 2017-10-31 15:30 UTC
